framework:
    secret: '%env(APP_SECRET)%'
    session:
        cookie_httponly: true
        cookie_samesite: lax
        cookie_secure: auto
    rate_limiter:
        contact_form:
            policy: sliding_window
            limit: 3
            interval: '15 minutes'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
