parameters:
    app.mailer_from: '%env(MAILER_FROM)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $mailerFrom: '%app.mailer_from%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
